config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  resources :posts do
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :category
  belongs_to :creator, class_name: 'User'
  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, class_name: 'PostLike', dependent: :destroy

  validates :title, presence: true, length: { minimum: 5, maximum: 255 }
  validates :body, presence: true, length: { minimum: 200, maximum: 4000 }
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  has_ancestry

  validates :content, presence: true, length: { minimum: 5, maximum: 1000 }
end

app/models/post_like.rb
# frozen_string_literal: true

class PostLike < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: :likes_count
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, inverse_of: :creator, dependent: :destroy
  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, class_name: 'PostLike', dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @post, flash: { success: t(:comment_success) }
    else
      redirect_to @post, flash: { error: @comment.errors.first.full_message }
    end
  end

  private

  def comment_params
    params.expect(post_comment: %i[content parent_id])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @post.likes.find_or_create_by(user: current_user)
    redirect_to @post
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = @post.likes.find_by(user: current_user)
    @like&.destroy
    redirect_to @post
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  def index
    @posts = Post.includes(:category, :creator).order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.new
    @comments = @post.comments.includes(:user).arrange(order: { created_at: :desc })
  end

  def new
    @post = Post.new
    @categories = Category.all
  end

  def create
    @post = current_user.posts.new(post_params)
    @categories = Category.all
    if @post.save
      redirect_to @post, flash: { success: t(:post_success) }
    else
      flash.now[:alert] = t(:post_failure)
      render :new, status: :unprocessable_content
    end
  end

  private

  def post_params
    params.expect(post: %i[title body category_id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def map_alert_type(type)
    map = {
      notice: 'info',
      error: 'danger',
      success: 'success'
    }
    map.fetch(type.to_sym, 'info')
  end
end

app/views/comments/_comment.html.slim
li
  p
    strong = comment.user.email
    | :
    = comment.content
    .mb-3
    - if user_signed_in?
      .collapse.mt-2 id="reply_form_#{comment.id}"
        = simple_form_for new_comment, url: post_comments_path(post) do |f|
          = f.hidden_field :parent_id, value: comment.id
          = f.input :content, label: false
          = f.button :submit, t(:reply), class: 'btn btn-dark btn-sm mt-1'
      = button_tag t(:reply),
        type: 'button',
        class: 'btn btn-outline-dark btn-sm mt-1 reply-toggle',
        data: { bs_toggle: 'collapse', bs_target: "#reply_form_#{comment.id}" }
  - if children.present?
    ul
      - children.each do |child, subchildren|
        = render partial: 'comments/comment', locals: { comment: child, children: subchildren, post: post, new_comment: PostComment.new }

app/views/home/index.html.slim
main.flex-shrink-0
  .container.mt-5
    h1.mb-4.text-center = t(:posts)
    .row
      - @posts.each do |post|
        .col-md-12
          .card.mb3
            .card-body
              h5.card-title = post.title
              p.card-text.mb-2 = truncate(post.body, length: 100)
              p.card-subtitle.text-muted.mb-2
                | #{t(:category)}: #{t("categories.#{post.category.name.downcase}")} | #{t(:author)}: #{post.creator.email}
              = link_to t(:read_more), post_path(post), class: 'btn btn-primary'
        .mb-3

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    = stylesheet_link_tag :app, 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
    - if defined?(Sentry) && Sentry.respond_to?(:get_trace_propagation_meta)
      - trace_meta = Sentry.get_trace_propagation_meta
      - if trace_meta.present?
        trace_meta.html_safe # rubocop:disable Rails/OutputSafety
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
  body.d-flex.flex-column.h-100
    header
      nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
        .container-fluid
          = link_to t(:blog), root_path, class: 'navbar-brand'
          button.navbar-toggler
            type = 'button'
            data-bs-toggle = 'collapse'
            data-bs-target = '#navbarCollapse'
            aria-controls = 'navbarCollapse'
            aria-expanded = 'false'
            aria-label = 'Toggle navigation'
            span.navbar-toggler-icon
          #navbarCollapse.collapse.navbar-collapse
            ul.navbar-nav.ms-auto.mb-2.mb-md-0
              - if user_signed_in?
                li.nav-item
                  = link_to t(:profile), edit_user_registration_path, class: 'nav-link'
                li.nav-item
                  = link_to t(:new_post), new_post_path, class: 'nav-link'
                li.nav-item
                  = link_to t(:log_out), destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link'
              - else
                li.nav-item
                  = link_to t(:log_in), new_user_session_path, class: 'nav-link'
                li.nav-item
                  = link_to t(:sign_up), new_user_registration_path, class: 'nav-link'
    = render 'shared/flash'
    = yield
    footer.footer.mt-auto.py-3.bg-light
      .container
        span.text-muted © #{Time.current.year} #{t(:blog)}. #{t(:all_rights)}

app/views/posts/new.html.slim
main.flex-shrink-0
  .container.mt-5
      h1 = t(:new_post)
      = simple_form_for @post do |f|
        .mb-3 = f.input :title, hint: t('simple_form.hints.post.title')
        .mb-3 = f.input :body, hint: t('simple_form.hints.post.body')
        .mb-3 = f.association :category, collection: @categories.map { |c| [t("categories.#{c.name.downcase}"), c.id] }, prompt: t('simple_form.hints.post.select_category')
        = f.button :submit, t('create_post'), class: 'btn btn-dark mt-3'

app/views/posts/show.html.slim
main.flex-shrink-0
.container.mt-5
    h1 = @post.title
    simple_format: p.lead = simple_format(@post.body)
    | #{t(:author)}: #{@post.creator.email}, #{t(:created_at)}: #{@post.created_at}
    .d-flex.align-items-center.mb-3
      = @post.likes_count
      - if user_signed_in?
        - if @post.likes.exists?(user: current_user)
          = button_to "\u2665", post_like_path(@post),
            method: :delete, class: 'heart-button border border-white bg-white fs-3 cursor-pointer py-0 px-1'
        - else
          = button_to "\u2661", post_likes_path(@post),
            method: :post, class: 'heart-button border border-white bg-white fs-3 cursor-pointer py-0 px-1'
      - else
        = "\u2661"
    - unless user_signed_in?
      p #{t(:cannot_like)}
    .lead.mt-5
      - if user_signed_in?
        = simple_form_for @comment, url: post_comments_path(@post) do |f|
          = f.input :content, label: false
          = f.button :submit, t(:add_comment), class: 'btn btn-dark mt-3'
      - else
        p #{t(:cannot_comment)}
    | #{t(:comments)}:
    - if @comments.present?
      ul
        - @comments.each do |comment, children|
          = render partial: 'comments/comment', locals: { comment: comment, children: children, post: @post, new_comment: PostComment.new }
    - else
      p.text-muted #{t(:no_comments)}
    = link_to t(:back_to_main), root_path, class: 'btn btn-secondary d-inline-block'

app/views/shared/_flash.html.slim
- flash.each do |type, msg|
    .mb-3
    div class=class_names('alert', "alert-#{map_alert_type(type)}") role='alert'
      = msg